name: Sample dummy buid WF
on:
  workflow_call:
env:
  REPOSITORY: "test-${{ github.event.inputs.target-runner-label }}"
  REGION: "europe"
jobs:
  sample-build:
    runs-on: ubuntu-latest
    steps:
      - name: Env check
        run: echo "Target ${{ github.event.inputs.target-runner-label}}"
      - name: Env check 2
        run: echo "ENV ${{ env.REPOSITORY }} und ${{ env.REGION }}"        
      - name: Sample output
        run: echo "Performing dummy build..."